"""Markdown summary report.

The layout is deliberate. Anything that would stop a reasonable person trading the
strategy goes at the very top, in plain language, before any table:

* synthetic data
* costs exceeding gross profit
* the account reaching zero
* position size relative to account size
* failure to beat the random benchmark

Tables come afterwards for the reader who wants the detail. A reader who only sees
the first screen should already know whether the answer is no.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import pandas as pd

from src.backtest.benchmark import RandomBenchmarkResult
from src.backtest.engine import BacktestResult
from src.backtest.sizing import format_risk_warning
from src.backtest.walkforward import WalkForwardResult
from src.config import Config, resolve_path
from src.data.loader import BarDataset
from src.metrics.performance import PerformanceMetrics, compute_metrics
from src.reporting import plots

log = logging.getLogger(__name__)


@dataclass
class StrategyReport:
    result: BacktestResult
    metrics: PerformanceMetrics
    benchmark: RandomBenchmarkResult | None = None
    walk_forward: WalkForwardResult | None = None
    sensitivity: pd.DataFrame = field(default_factory=pd.DataFrame)
    label: str = ""

    @property
    def name(self) -> str:
        return self.label or self.result.strategy

    @classmethod
    def build(cls, result: BacktestResult, **kwargs) -> "StrategyReport":
        return cls(result=result, metrics=compute_metrics(result), **kwargs)


# ---------------------------------------------------------------------- #
def _fmt(value, spec: str = ",.2f", dash: str = "-") -> str:
    if value is None:
        return dash
    if isinstance(value, float) and not np.isfinite(value):
        return dash
    try:
        return format(value, spec)
    except (TypeError, ValueError):
        return str(value)


def _table(headers: list[str], rows: list[list[str]]) -> str:
    lines = ["| " + " | ".join(headers) + " |",
             "|" + "|".join("---" for _ in headers) + "|"]
    lines += ["| " + " | ".join(row) + " |" for row in rows]
    return "\n".join(lines)


# ---------------------------------------------------------------------- #
def headline_verdict(
    reports: list[StrategyReport], dataset: BarDataset, cfg: Config
) -> list[str]:
    lines: list[str] = ["## Verdict", ""]

    if dataset.provenance.is_synthetic:
        lines += [
            "> **THESE RESULTS ARE ON SYNTHETIC DATA.** The bars were generated by a "
            "driftless random-walk model, not observed in any market. Nothing here is "
            "evidence about whether a strategy works on real gold. Point "
            "`data.adapter` at a real source before drawing any conclusion.",
            "",
        ]

    tradeable = [r for r in reports if r.name != "buy_and_hold"]
    verdicts: list[str] = []

    for report in tradeable:
        metrics, result = report.metrics, report.result
        name = report.name
        reasons: list[str] = []

        if result.was_ruined:
            reasons.append(
                f"the account reached zero on {result.ruin_time:%Y-%m-%d} and was stopped out"
            )
        if result.costs_exceed_gross_profit:
            reasons.append(
                f"costs of {result.total_costs:,.2f} USD exceeded gross profit of "
                f"{result.gross_pnl:,.2f} USD, so the strategy was right about direction "
                "and still lost money"
            )
        elif metrics.net_pnl_usd <= 0:
            reasons.append(f"net P&L was {metrics.net_pnl_usd:,.2f} USD")
        if report.benchmark is not None and report.benchmark.n_runs and not report.benchmark.passes:
            reasons.append(
                f"it sits at the {report.benchmark.strategy_percentile:.0f}th percentile of "
                f"{report.benchmark.n_runs} random-entry runs with the same trade profile, "
                f"below the {report.benchmark.percentile_threshold:.0f}th percentile bar"
            )
        wf = report.walk_forward
        if wf is not None and wf.deflated is not None and not wf.deflated.is_significant:
            reasons.append(
                f"the deflated Sharpe ratio is {wf.deflated.deflated_sharpe:.2f} after "
                f"{wf.total_trials} parameter trials, short of 0.95"
            )

        if reasons:
            verdicts.append(f"- **{name}: no demonstrated edge.** " + "; ".join(reasons) + ".")
        else:
            verdicts.append(
                f"- **{name}: cleared every check in this report.** Net "
                f"{metrics.net_pnl_usd:,.2f} USD out of sample, above the random benchmark "
                "and above the deflated-Sharpe bar. That is a reason to keep testing it, "
                "on more data and out of sample again, not a reason to trade it."
            )

    lines += verdicts or ["- No tradeable strategies were run."]
    lines.append("")

    risky = [r for r in reports if r.result.risk is not None and
             (r.result.risk.breaches_threshold or r.result.risk.min_lot_unaffordable)]
    if risky:
        lines.append("```")
        lines += format_risk_warning(risky[0].result.risk)
        lines.append("```")
        lines.append("")
    return lines


def account_reality_section(reports: list[StrategyReport], cfg: Config) -> list[str]:
    """What the configured account size means in practice."""
    risks = [r.result.risk for r in reports if r.result.risk is not None]
    if not risks:
        return []
    risk = risks[0]
    capital = reports[0].result.initial_capital

    lines = ["## What this account size can actually do", ""]
    lines.append(
        f"Starting capital is **{capital:,.2f} USD**. The smallest position this broker "
        f"allows is {risk.min_position_oz:.2f} oz ({risk.min_position_oz / 100:.2f} lots)."
    )
    lines.append("")
    lines.append(_table(
        ["Quantity", "Value"],
        [
            ["Median ATR", f"{risk.atr_usd_per_oz:,.2f} USD/oz"],
            ["Median daily range", f"{risk.daily_range_usd_per_oz:,.2f} USD/oz"],
            ["Risk per ATR at the minimum position",
             f"{risk.min_risk_per_atr_pct:,.1f}% of equity"],
            ["Risk per daily range at the traded position",
             f"{_fmt(risk.risk_per_daily_range_pct, ',.1f')}% of equity"],
            [f"Minimum viable equity for a {risk.risk_fraction_per_trade:.1%} risk rule "
             f"({risk.stop_atr_multiple:g}x ATR stop)",
             f"**{_fmt(risk.min_viable_equity_usd, ',.0f')} USD**"],
        ],
    ))
    lines.append("")
    if risk.min_lot_unaffordable:
        lines.append(
            f"At {capital:,.0f} USD the minimum tradeable position risks "
            f"{risk.min_risk_per_atr_pct:.0f}% of the account per ATR of adverse movement. "
            "There is no position sizing rule that fixes this; the instrument contract "
            "size is simply too large relative to the account. The equity level at which "
            f"the configured risk rule becomes followable is about "
            f"{_fmt(risk.min_viable_equity_usd, ',.0f')} USD."
        )
        lines.append("")
    return lines


def performance_tables(reports: list[StrategyReport]) -> list[str]:
    lines = ["## Out-of-sample performance", ""]

    lines.append("### Returns and risk")
    lines.append("")
    lines.append(_table(
        ["Strategy", "Net P&L (USD)", "Net return", "Final equity (USD)",
         "CAGR (net)", "Sharpe", "Sortino", "Calmar", "Max DD", "Time underwater"],
        [[
            r.name,
            _fmt(r.metrics.net_pnl_usd),
            _fmt(r.metrics.total_return_net, ".2%"),
            _fmt(r.metrics.final_equity_net_usd),
            _fmt(r.metrics.cagr_net, ".2%"),
            _fmt(r.metrics.sharpe, ".2f"),
            _fmt(r.metrics.sortino, ".2f"),
            _fmt(r.metrics.calmar, ".2f"),
            _fmt(r.metrics.max_drawdown_fraction, ".2%"),
            _fmt(r.metrics.time_underwater_fraction, ".1%"),
        ] for r in reports],
    ))
    lines.append("")

    lines.append("### Gross, costs and net")
    lines.append("")
    lines.append(_table(
        ["Strategy", "Gross P&L (USD)", "Total costs (USD)", "Net P&L (USD)",
         "Cost drag (% of gross profit)", "Cost per trade (USD)",
         "Spread", "Slippage", "Commission", "Financing"],
        [[
            r.name,
            _fmt(r.metrics.gross_pnl_usd),
            _fmt(r.metrics.total_cost_usd),
            _fmt(r.metrics.net_pnl_usd),
            _fmt(r.metrics.cost_drag_pct_of_gross_profit, ",.1f"),
            _fmt(r.metrics.cost_per_trade_usd, ",.3f"),
            _fmt(r.metrics.cost_breakdown_usd.get("spread")),
            _fmt(r.metrics.cost_breakdown_usd.get("slippage")),
            _fmt(r.metrics.cost_breakdown_usd.get("commission")),
            _fmt(r.metrics.cost_breakdown_usd.get("financing")),
        ] for r in reports],
    ))
    lines.append("")

    lines.append("### Trading")
    lines.append("")
    lines.append(_table(
        ["Strategy", "Trades", "Trades/year", "Win rate", "Profit factor",
         "Avg win (USD)", "Avg loss (USD)", "Expectancy (USD)", "Expectancy (R)", "Exposure"],
        [[
            r.name,
            f"{r.metrics.n_trades:,}",
            _fmt(r.metrics.trades_per_year, ",.0f"),
            _fmt(r.metrics.win_rate, ".1%"),
            _fmt(r.metrics.profit_factor, ".2f"),
            _fmt(r.metrics.avg_win_usd),
            _fmt(r.metrics.avg_loss_usd),
            _fmt(r.metrics.expectancy_usd, ",.3f"),
            _fmt(r.metrics.expectancy_r, ",.3f"),
            _fmt(r.metrics.exposure, ".1%"),
        ] for r in reports],
    ))
    lines.append("")
    return lines


def comparison_section(reports: list[StrategyReport]) -> list[str]:
    baseline = next((r for r in reports if r.name == "buy_and_hold"), None)
    lines = ["## Comparison against the benchmarks", ""]
    rows = []
    for report in reports:
        against_bh = (
            _fmt(report.metrics.net_pnl_usd - baseline.metrics.net_pnl_usd)
            if baseline is not None else "-"
        )
        bench = report.benchmark
        if bench is not None and bench.n_runs:
            pct = f"{bench.strategy_percentile:.1f}th"
            threshold = _fmt(bench.threshold_value)
            passed = "yes" if bench.passes else "**no**"
            median = _fmt(float(np.median(bench.net_pnl)))
        else:
            pct = threshold = passed = median = "-"
        rows.append([
            report.name, _fmt(report.metrics.net_pnl_usd), against_bh,
            median, threshold, pct, passed,
        ])
    lines.append(_table(
        ["Strategy", "Net P&L (USD)", "vs buy & hold (USD)", "Random median (USD)",
         "Random 95th pct (USD)", "Strategy percentile", "Beats random?"],
        rows,
    ))
    lines.append("")
    lines.append(
        "A strategy that does not sit outside the 95th percentile of the random-entry "
        "distribution has not demonstrated anything: it traded gold as often as a random "
        "number generator and did no better."
    )
    lines.append("")
    return lines


def walk_forward_section(reports: list[StrategyReport]) -> list[str]:
    with_wf = [r for r in reports if r.walk_forward is not None]
    if not with_wf:
        return []
    lines = ["## Walk-forward validation", "",
             "Anchored walk-forward. Parameters are fitted on each in-sample window and "
             "applied unchanged to the following out-of-sample window; only the "
             "concatenated out-of-sample record is reported above.", ""]
    for report in with_wf:
        wf = report.walk_forward
        lines.append(f"### {report.name}")
        lines.append("")
        folds = wf.folds_frame()
        if len(folds):
            display = folds.drop(columns=["train_start"])
            for col in ("train_end", "test_start", "test_end"):
                display[col] = pd.to_datetime(display[col]).dt.strftime("%Y-%m-%d")
            rows = [
                [_fmt(value, ",.4f") if isinstance(value, float) else str(value)
                 for value in row]
                for row in display.itertuples(index=False)
            ]
            lines.append(_table([str(c) for c in display.columns], rows))
            lines.append("")
        lines.append(
            f"- Parameter combinations evaluated: **{wf.total_trials}** "
            f"({len(wf.folds)} folds x {wf.folds[0].n_combinations if wf.folds else 0} combinations)"
        )
        lines.append(f"- Purge/embargo at each boundary: {wf.folds[0].embargo_bars if wf.folds else 0} bars")
        if wf.deflated is not None:
            d = wf.deflated
            lines.append(
                f"- Raw Sharpe (per bar): {d.sharpe_observed:.4f}; selection-bias "
                f"threshold from {d.n_trials} trials: {d.sharpe_threshold:.4f}"
            )
            lines.append(
                f"- Probabilistic Sharpe: {d.probabilistic_sharpe:.3f}; "
                f"**deflated Sharpe: {d.deflated_sharpe:.3f}** "
                f"({'clears' if d.is_significant else 'does not clear'} the 0.95 bar)"
            )
        for warning in wf.warnings:
            lines.append(f"- warning: {warning}")
        lines.append("")
    return lines


def data_and_costs_section(dataset: BarDataset, reports: list[StrategyReport]) -> list[str]:
    lines = ["## Data and cost assumptions", "", "### Data", ""]
    lines += [f"- {line}" for line in dataset.describe()]
    lines += ["", "### Cost model", ""]
    if reports:
        lines += [f"- {line}" for line in reports[0].result.cost_lines]
    lines += [
        "",
        "Fills follow one rule with no exceptions: a signal generated on bar *t* fills at "
        "the **open of bar t+1**, with slippage applied against the trade. Never at the "
        "signal bar close, never at the high or the low.",
        "",
    ]
    return lines


def warnings_section(reports: list[StrategyReport]) -> list[str]:
    rows = [(r.name, w) for r in reports for w in r.result.warnings]
    rows += [(r.name, n) for r in reports for n in r.metrics.notes]
    if not rows:
        return []
    lines = ["## Warnings raised during the run", ""]
    lines += [f"- **{name}**: {message}" for name, message in rows]
    lines.append("")
    return lines


# ---------------------------------------------------------------------- #
def build_markdown(
    reports: list[StrategyReport], dataset: BarDataset, cfg: Config, assets: dict
) -> str:
    generated = pd.Timestamp.now(tz="UTC").strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# XAU/USD backtest report",
        "",
        f"Generated {generated}. Research only; this engine places no orders.",
        "",
    ]
    lines += headline_verdict(reports, dataset, cfg)
    lines += account_reality_section(reports, cfg)
    lines += performance_tables(reports)
    lines += comparison_section(reports)
    lines += walk_forward_section(reports)
    lines += data_and_costs_section(dataset, reports)
    lines += warnings_section(reports)

    if assets:
        lines += ["## Files", ""]
        for name, paths in assets.items():
            for path in paths:
                lines.append(f"- `{path}` ({name})")
        lines.append("")
    return "\n".join(lines)


def write_report(
    reports: list[StrategyReport],
    dataset: BarDataset,
    cfg: Config,
    *,
    out_dir: str | Path | None = None,
) -> Path:
    out_dir = resolve_path(out_dir or cfg.get("reporting.output_dir", "reports"))
    out_dir.mkdir(parents=True, exist_ok=True)
    assets: dict[str, list[str]] = {"trade log": [], "equity curve": [],
                                    "drawdown": [], "random benchmark": [],
                                    "parameter sensitivity": []}

    write_trades = bool(cfg.get("reporting.write_trade_log", True))
    write_plots = bool(cfg.get("reporting.write_plots", True))

    for report in reports:
        slug = report.name.replace(" ", "_").replace("(", "").replace(")", "")
        if write_trades and len(report.result.trades):
            path = out_dir / f"trades_{slug}.csv"
            report.result.trades.to_csv(path, index=False)
            assets["trade log"].append(str(path.relative_to(out_dir.parent)))

        if not write_plots:
            continue

        assets["equity curve"].append(str(plots.plot_equity(
            report.result.equity_net, report.result.equity_gross, report.result.costs_cum,
            title=f"{report.name} - gross vs net equity",
            path=out_dir / f"equity_{slug}.png",
            initial_capital=report.result.initial_capital,
            ruin_time=report.result.ruin_time,
        ).relative_to(out_dir.parent)))

        assets["drawdown"].append(str(plots.plot_drawdown(
            report.result.equity_net,
            title=f"{report.name} - drawdown (net)",
            path=out_dir / f"drawdown_{slug}.png",
        ).relative_to(out_dir.parent)))

        if report.benchmark is not None and report.benchmark.n_runs:
            assets["random benchmark"].append(str(plots.plot_random_benchmark(
                report.benchmark.net_pnl, report.benchmark.strategy_net_pnl,
                percentile=report.benchmark.percentile_threshold,
                title=f"{report.name} vs {report.benchmark.n_runs} random-entry runs",
                path=out_dir / f"random_benchmark_{slug}.png",
            ).relative_to(out_dir.parent)))

        if len(report.sensitivity):
            path = plots.plot_parameter_sensitivity(
                report.sensitivity,
                title=f"{report.name} - parameter sensitivity",
                path=out_dir / f"sensitivity_{slug}.png",
            )
            if path is not None:
                assets["parameter sensitivity"].append(str(path.relative_to(out_dir.parent)))
            report.sensitivity.to_csv(out_dir / f"sensitivity_{slug}.csv", index=False)

    assets = {k: v for k, v in assets.items() if v}
    markdown = build_markdown(reports, dataset, cfg, assets)
    summary_path = out_dir / "summary.md"
    summary_path.write_text(markdown, encoding="utf-8")
    log.info("report written to %s", summary_path)
    return summary_path
